#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from .isbntools import get_canonical_isbn


def isbn_stdin_validate():
    """ Helper function to validate ISBNs from sys.stdin

    It will output all valide ISBNs that receive from input.

    Usage:
    cat ISBNs| isbn_stdin_validate
    """
    for line in sys.stdin:
        line = line.strip()
        get_canonical_isbn(line)
       
        
if __name__ == "__main__":
    isbn_stdin_validate()
